### PR TITLE
Update lock file

### PR DESCRIPTION
**Pull request by jbrownson**
Had a similar problem as https://github.com/bsansouci/reasonglexampleproject/issues/2 w/ this repo

### CODE REVIEW

**Comment by bsansouci** [comment]
Do you mind adding a package-lock.json as well? You can just run npm install with npm5 or npm6 to generate it.

**Comment by jbrownson** [comment]
I'm getting a different error now: 

``` 
We've found a bug for you!
  /Users/jake/Downloads/rewitness/src/index.re 454:25-32
  
  452 │ let window = Gl.Window.init argv::Sys.argv;
  453 │ 
  454 │ Gl.Window.setWindowSize ::window width::windowSize height::windowSize
        ;
  455 │ 
  456 │ let env = buildGlEnv ::window;
  
  This is:
    ?screen:string -> Gl.Window.t
  But somewhere wanted:
    Gl.Window.t
```

**Comment by jbrownson** [comment]
I had it working, I must have reset some local change I had that either something automatically did or I did but forgot about I think

**Comment by jbrownson** [comment]
yeah I think I had made this change manually, the API must have changed

**Comment by bsansouci** [comment]
Good call. Thank for the fix.

**Pull request merged**
